import { Injectable } from "@nestjs/common";
import { PrismaService } from "@amdox/database";
import { AuthUser } from "../../auth/interfaces/auth-user.interface";
import {
  WorkOrderStatus,
  PurchaseOrderStatus,
} from "@amdox/database/generated";
import { PurchaseService } from "../../purchase/purchase.service";

@Injectable()
export class MRPService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly purchaseService: PurchaseService,
  ) {}

  async calculateRequirements(user: AuthUser) {
    const tenantId = user.tenantId!;

    // 1. Fetch active work orders
    const activeWOs = await this.prisma.workOrder.findMany({
      where: {
        tenantId,
        status: {
          in: [
            WorkOrderStatus.APPROVED,
            WorkOrderStatus.IN_PROGRESS,
            WorkOrderStatus.PENDING_APPROVAL,
          ],
        },
        deletedAt: null,
      },
      include: {
        bom: {
          include: {
            items: {
              include: {
                product: true,
              },
            },
          },
        },
      },
    });

    // 2. Aggregate demand per product
    const demandMap = new Map<
      string,
      {
        product: { name: string; sku: string } & Record<string, unknown>;
        quantity: number;
      }
    >();
    for (const wo of activeWOs) {
      for (const item of wo.bom.items) {
        const qtyRequired =
          Number(item.quantity) *
          Number(wo.quantity) *
          (1 + Number(item.scrapFactor) / 100);
        const existing = demandMap.get(item.productId);
        if (existing) {
          existing.quantity += qtyRequired;
        } else {
          demandMap.set(item.productId, {
            product: item.product,
            quantity: qtyRequired,
          });
        }
      }
    }

    // 3. Find current stock levels and open POs
    const results = [];
    for (const [productId, demand] of demandMap.entries()) {
      // Stock Level sum
      const stockSummary = await this.prisma.stock.aggregate({
        where: { tenantId, productId },
        _sum: { quantity: true },
      });
      const stockOnHand = Number(stockSummary._sum.quantity || 0);

      // Open POs (Pending delivery)
      const openPOItems = await this.prisma.purchaseOrderItem.findMany({
        where: {
          tenantId,
          productId,
          purchaseOrder: {
            status: {
              in: [PurchaseOrderStatus.DRAFT, PurchaseOrderStatus.APPROVED],
            },
            deletedAt: null,
          },
        },
      });

      const poQuantity = openPOItems.reduce(
        (acc, item) => acc + Number(item.quantity),
        0,
      );

      const netShortage = stockOnHand + poQuantity - demand.quantity;

      results.push({
        productId,
        productName: demand.product.name,
        sku: demand.product.sku,
        demandQuantity: demand.quantity,
        stockOnHand,
        openPurchaseQuantity: poQuantity,
        netShortage: netShortage < 0 ? Math.abs(netShortage) : 0,
        recommendation: netShortage < 0 ? "BUY" : "OK",
      });
    }

    return results;
  }

  async runMRP(user: AuthUser) {
    const requirements = await this.calculateRequirements(user);
    const buyList = requirements.filter((r) => r.recommendation === "BUY");

    if (buyList.length === 0) {
      return {
        message: "MRP run complete. No shortages detected.",
        purchaseOrdersCreated: [],
      };
    }

    // Group shortages and create a draft purchase order
    const poItems = buyList.map((r) => ({
      productId: r.productId,
      quantity: r.netShortage,
      unitPrice: 10.0, // Default fallback price
    }));

    const po = await this.purchaseService.create(
      {
        supplierName: "MRP Auto Supplier",
        expectedDeliveryDate: new Date(
          Date.now() + 7 * 24 * 60 * 60 * 1000,
        ).toISOString(),
        notes: "Automatically generated by MRP Run",
        items: poItems,
      },
      user,
    );

    return {
      message:
        "MRP run complete. Shortages detected and draft purchase order generated.",
      purchaseOrdersCreated: [po],
      requirements,
    };
  }
}
