export enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = "AUTH.INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED = "AUTH.UNAUTHORIZED",
  AUTH_FORBIDDEN = "AUTH.FORBIDDEN",
  USER_NOT_FOUND = "USER.NOT_FOUND",
  TENANT_NOT_FOUND = "TENANT.NOT_FOUND",
  ROLE_NOT_FOUND = "ROLE.NOT_FOUND",
  DATABASE_CONFLICT = "DATABASE.CONFLICT",
  VALIDATION_INVALID_INPUT = "VALIDATION.INVALID_INPUT",
  SYSTEM_INTERNAL_ERROR = "SYSTEM.INTERNAL_ERROR",
}
